// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"context"

	"github.com/gera9/blog/internal/models"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPostsRepository creates a new instance of MockPostsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostsRepository {
	mock := &MockPostsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostsRepository is an autogenerated mock type for the PostsRepository type
type MockPostsRepository struct {
	mock.Mock
}

type MockPostsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostsRepository) EXPECT() *MockPostsRepository_Expecter {
	return &MockPostsRepository_Expecter{mock: &_m.Mock}
}

// CreatePost provides a mock function for the type MockPostsRepository
func (_mock *MockPostsRepository) CreatePost(ctx context.Context, post models.Post) (uuid.UUID, error) {
	ret := _mock.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for CreatePost")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Post) (uuid.UUID, error)); ok {
		return returnFunc(ctx, post)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Post) uuid.UUID); ok {
		r0 = returnFunc(ctx, post)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Post) error); ok {
		r1 = returnFunc(ctx, post)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostsRepository_CreatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePost'
type MockPostsRepository_CreatePost_Call struct {
	*mock.Call
}

// CreatePost is a helper method to define mock.On call
//   - ctx context.Context
//   - post models.Post
func (_e *MockPostsRepository_Expecter) CreatePost(ctx interface{}, post interface{}) *MockPostsRepository_CreatePost_Call {
	return &MockPostsRepository_CreatePost_Call{Call: _e.mock.On("CreatePost", ctx, post)}
}

func (_c *MockPostsRepository_CreatePost_Call) Run(run func(ctx context.Context, post models.Post)) *MockPostsRepository_CreatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Post
		if args[1] != nil {
			arg1 = args[1].(models.Post)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostsRepository_CreatePost_Call) Return(uUID uuid.UUID, err error) *MockPostsRepository_CreatePost_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockPostsRepository_CreatePost_Call) RunAndReturn(run func(ctx context.Context, post models.Post) (uuid.UUID, error)) *MockPostsRepository_CreatePost_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePostById provides a mock function for the type MockPostsRepository
func (_mock *MockPostsRepository) DeletePostById(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePostById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostsRepository_DeletePostById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePostById'
type MockPostsRepository_DeletePostById_Call struct {
	*mock.Call
}

// DeletePostById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockPostsRepository_Expecter) DeletePostById(ctx interface{}, id interface{}) *MockPostsRepository_DeletePostById_Call {
	return &MockPostsRepository_DeletePostById_Call{Call: _e.mock.On("DeletePostById", ctx, id)}
}

func (_c *MockPostsRepository_DeletePostById_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockPostsRepository_DeletePostById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostsRepository_DeletePostById_Call) Return(err error) *MockPostsRepository_DeletePostById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostsRepository_DeletePostById_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockPostsRepository_DeletePostById_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllPosts provides a mock function for the type MockPostsRepository
func (_mock *MockPostsRepository) FindAllPosts(ctx context.Context, limit int, offset int, authorId uuid.UUID) ([]models.Post, error) {
	ret := _mock.Called(ctx, limit, offset, authorId)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPosts")
	}

	var r0 []models.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, uuid.UUID) ([]models.Post, error)); ok {
		return returnFunc(ctx, limit, offset, authorId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, uuid.UUID) []models.Post); ok {
		r0 = returnFunc(ctx, limit, offset, authorId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, limit, offset, authorId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostsRepository_FindAllPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllPosts'
type MockPostsRepository_FindAllPosts_Call struct {
	*mock.Call
}

// FindAllPosts is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
//   - authorId uuid.UUID
func (_e *MockPostsRepository_Expecter) FindAllPosts(ctx interface{}, limit interface{}, offset interface{}, authorId interface{}) *MockPostsRepository_FindAllPosts_Call {
	return &MockPostsRepository_FindAllPosts_Call{Call: _e.mock.On("FindAllPosts", ctx, limit, offset, authorId)}
}

func (_c *MockPostsRepository_FindAllPosts_Call) Run(run func(ctx context.Context, limit int, offset int, authorId uuid.UUID)) *MockPostsRepository_FindAllPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPostsRepository_FindAllPosts_Call) Return(posts []models.Post, err error) *MockPostsRepository_FindAllPosts_Call {
	_c.Call.Return(posts, err)
	return _c
}

func (_c *MockPostsRepository_FindAllPosts_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int, authorId uuid.UUID) ([]models.Post, error)) *MockPostsRepository_FindAllPosts_Call {
	_c.Call.Return(run)
	return _c
}

// FindPostByIdAndAuthorId provides a mock function for the type MockPostsRepository
func (_mock *MockPostsRepository) FindPostByIdAndAuthorId(ctx context.Context, id uuid.UUID, authorId uuid.UUID) (models.Post, error) {
	ret := _mock.Called(ctx, id, authorId)

	if len(ret) == 0 {
		panic("no return value specified for FindPostByIdAndAuthorId")
	}

	var r0 models.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (models.Post, error)); ok {
		return returnFunc(ctx, id, authorId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) models.Post); ok {
		r0 = returnFunc(ctx, id, authorId)
	} else {
		r0 = ret.Get(0).(models.Post)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, authorId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostsRepository_FindPostByIdAndAuthorId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPostByIdAndAuthorId'
type MockPostsRepository_FindPostByIdAndAuthorId_Call struct {
	*mock.Call
}

// FindPostByIdAndAuthorId is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - authorId uuid.UUID
func (_e *MockPostsRepository_Expecter) FindPostByIdAndAuthorId(ctx interface{}, id interface{}, authorId interface{}) *MockPostsRepository_FindPostByIdAndAuthorId_Call {
	return &MockPostsRepository_FindPostByIdAndAuthorId_Call{Call: _e.mock.On("FindPostByIdAndAuthorId", ctx, id, authorId)}
}

func (_c *MockPostsRepository_FindPostByIdAndAuthorId_Call) Run(run func(ctx context.Context, id uuid.UUID, authorId uuid.UUID)) *MockPostsRepository_FindPostByIdAndAuthorId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPostsRepository_FindPostByIdAndAuthorId_Call) Return(post models.Post, err error) *MockPostsRepository_FindPostByIdAndAuthorId_Call {
	_c.Call.Return(post, err)
	return _c
}

func (_c *MockPostsRepository_FindPostByIdAndAuthorId_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, authorId uuid.UUID) (models.Post, error)) *MockPostsRepository_FindPostByIdAndAuthorId_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePostByIdAndAuthorId provides a mock function for the type MockPostsRepository
func (_mock *MockPostsRepository) UpdatePostByIdAndAuthorId(ctx context.Context, id uuid.UUID, authorId uuid.UUID, post models.Post) error {
	ret := _mock.Called(ctx, id, authorId, post)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePostByIdAndAuthorId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, models.Post) error); ok {
		r0 = returnFunc(ctx, id, authorId, post)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostsRepository_UpdatePostByIdAndAuthorId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePostByIdAndAuthorId'
type MockPostsRepository_UpdatePostByIdAndAuthorId_Call struct {
	*mock.Call
}

// UpdatePostByIdAndAuthorId is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - authorId uuid.UUID
//   - post models.Post
func (_e *MockPostsRepository_Expecter) UpdatePostByIdAndAuthorId(ctx interface{}, id interface{}, authorId interface{}, post interface{}) *MockPostsRepository_UpdatePostByIdAndAuthorId_Call {
	return &MockPostsRepository_UpdatePostByIdAndAuthorId_Call{Call: _e.mock.On("UpdatePostByIdAndAuthorId", ctx, id, authorId, post)}
}

func (_c *MockPostsRepository_UpdatePostByIdAndAuthorId_Call) Run(run func(ctx context.Context, id uuid.UUID, authorId uuid.UUID, post models.Post)) *MockPostsRepository_UpdatePostByIdAndAuthorId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 models.Post
		if args[3] != nil {
			arg3 = args[3].(models.Post)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPostsRepository_UpdatePostByIdAndAuthorId_Call) Return(err error) *MockPostsRepository_UpdatePostByIdAndAuthorId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostsRepository_UpdatePostByIdAndAuthorId_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, authorId uuid.UUID, post models.Post) error) *MockPostsRepository_UpdatePostByIdAndAuthorId_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsersRepository creates a new instance of MockUsersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersRepository {
	mock := &MockUsersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsersRepository is an autogenerated mock type for the UsersRepository type
type MockUsersRepository struct {
	mock.Mock
}

type MockUsersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersRepository) EXPECT() *MockUsersRepository_Expecter {
	return &MockUsersRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) CreateUser(ctx context.Context, user models.User) (uuid.UUID, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.User) (uuid.UUID, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.User) uuid.UUID); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUsersRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user models.User
func (_e *MockUsersRepository_Expecter) CreateUser(ctx interface{}, user interface{}) *MockUsersRepository_CreateUser_Call {
	return &MockUsersRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockUsersRepository_CreateUser_Call) Run(run func(ctx context.Context, user models.User)) *MockUsersRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.User
		if args[1] != nil {
			arg1 = args[1].(models.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_CreateUser_Call) Return(uUID uuid.UUID, err error) *MockUsersRepository_CreateUser_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockUsersRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user models.User) (uuid.UUID, error)) *MockUsersRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserById provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) DeleteUserById(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersRepository_DeleteUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserById'
type MockUsersRepository_DeleteUserById_Call struct {
	*mock.Call
}

// DeleteUserById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsersRepository_Expecter) DeleteUserById(ctx interface{}, id interface{}) *MockUsersRepository_DeleteUserById_Call {
	return &MockUsersRepository_DeleteUserById_Call{Call: _e.mock.On("DeleteUserById", ctx, id)}
}

func (_c *MockUsersRepository_DeleteUserById_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsersRepository_DeleteUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_DeleteUserById_Call) Return(err error) *MockUsersRepository_DeleteUserById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersRepository_DeleteUserById_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockUsersRepository_DeleteUserById_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllUsers provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) FindAllUsers(ctx context.Context, limit int, offset int) ([]models.User, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindAllUsers")
	}

	var r0 []models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]models.User, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []models.User); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_FindAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllUsers'
type MockUsersRepository_FindAllUsers_Call struct {
	*mock.Call
}

// FindAllUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockUsersRepository_Expecter) FindAllUsers(ctx interface{}, limit interface{}, offset interface{}) *MockUsersRepository_FindAllUsers_Call {
	return &MockUsersRepository_FindAllUsers_Call{Call: _e.mock.On("FindAllUsers", ctx, limit, offset)}
}

func (_c *MockUsersRepository_FindAllUsers_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockUsersRepository_FindAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersRepository_FindAllUsers_Call) Return(users []models.User, err error) *MockUsersRepository_FindAllUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUsersRepository_FindAllUsers_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]models.User, error)) *MockUsersRepository_FindAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserById provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) FindUserById(ctx context.Context, id uuid.UUID) (models.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindUserById")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_FindUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserById'
type MockUsersRepository_FindUserById_Call struct {
	*mock.Call
}

// FindUserById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUsersRepository_Expecter) FindUserById(ctx interface{}, id interface{}) *MockUsersRepository_FindUserById_Call {
	return &MockUsersRepository_FindUserById_Call{Call: _e.mock.On("FindUserById", ctx, id)}
}

func (_c *MockUsersRepository_FindUserById_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUsersRepository_FindUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_FindUserById_Call) Return(user models.User, err error) *MockUsersRepository_FindUserById_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_FindUserById_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (models.User, error)) *MockUsersRepository_FindUserById_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserById provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) UpdateUserById(ctx context.Context, id uuid.UUID, user models.User) error {
	ret := _mock.Called(ctx, id, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.User) error); ok {
		r0 = returnFunc(ctx, id, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersRepository_UpdateUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserById'
type MockUsersRepository_UpdateUserById_Call struct {
	*mock.Call
}

// UpdateUserById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - user models.User
func (_e *MockUsersRepository_Expecter) UpdateUserById(ctx interface{}, id interface{}, user interface{}) *MockUsersRepository_UpdateUserById_Call {
	return &MockUsersRepository_UpdateUserById_Call{Call: _e.mock.On("UpdateUserById", ctx, id, user)}
}

func (_c *MockUsersRepository_UpdateUserById_Call) Run(run func(ctx context.Context, id uuid.UUID, user models.User)) *MockUsersRepository_UpdateUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 models.User
		if args[2] != nil {
			arg2 = args[2].(models.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersRepository_UpdateUserById_Call) Return(err error) *MockUsersRepository_UpdateUserById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersRepository_UpdateUserById_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, user models.User) error) *MockUsersRepository_UpdateUserById_Call {
	_c.Call.Return(run)
	return _c
}
